import React from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';

function Home() {
  const router = useRouter();

  /**
   * Application get roomId from latest path section
   */
  const createRoom = () => {
    // Do not use the symbol "_" in room address
    router.push(`/room-${new Date().getTime()}?uid=1`);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button type="button" onClick={createRoom}>
        Create room
      </button>
    </div>
  );
}

export default Home;
