import React, { useMemo } from 'react';
import Link from 'next/link';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

function Home() {
  const href = useMemo(() => `/room/${new Date().getTime()}?uid=${new Date().getTime() + 1}`, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href={href}>
        <button type="button">Create room</button>
      </Link>
    </div>
  );
}

export default Home;
