import type { NextPage } from 'next';
import Head from 'next/head';
import Uyem from '../../../packages/client/src/package/Main';
import styles from '../styles/Home.module.css';

/**
 * Application get roomId from latest path section
 */
const createRoom = () => {
  // Do not use the symbol "_" in room address
  window.location.href = `/path/to/room-${new Date().getTime()}?uid=1`;
};

const Home: NextPage = () => {
  const isHall = window.location.pathname === '/';
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isHall ? (
        <button type="button" onClick={createRoom}>
          Create room
        </button>
      ) : (
        <Uyem
          room={{
            server: 'localhost',
            port: 3001,
            iceServers: [
              {
                urls: ['stun:127.0.0.1:3478'],
              },
              {
                urls: ['turn:127.0.0.2:3478'],
                username: 'username',
                credential: 'password',
              },
            ],
            userId: window.location.search.replace(/\?uid=/, ''),
          }}
        />
      )}
    </div>
  );
};

export default Home;
